# The value of AppId uniquely identifies this application.
# Do not use the same AppId value in installers for other applications.
app_id: 
publisher: RoBoT_095
publisher_url: https://github.com/RoBoT_095/printnotes
display_name: Print(Notes)
create_desktop_icon: true
# See: https://jrsoftware.org/ishelp/index.php?topic=setup_defaultdirname
# install_dir_name: ""
setup_icon_file: windows\runner\resources\app_icon.ico
locales:
  - en
